list( APPEND fms_headers 
FMS/mpp/include/mpp_do_global_field.h
FMS/mpp/include/mpp_read_distributed_ascii.h
FMS/mpp/include/mpp_transmit_mpi.h
FMS/mpp/include/mpp_write_unlimited_axis.h
FMS/mpp/include/mpp_write_2Ddecomp.h
FMS/mpp/include/mpp_reduce_sma.h
FMS/mpp/include/mpp_error_a_a.h
FMS/mpp/include/mpp_unstruct_pass_data.h
FMS/mpp/include/mpp_alltoall_nocomm.h
FMS/mpp/include/mpp_update_domains2D_ad.h
FMS/mpp/include/mpp_global_sum.h
FMS/mpp/include/mpp_sum_nocomm.h
FMS/mpp/include/mpp_do_checkV.h
FMS/mpp/include/mpp_write.h
FMS/mpp/include/mpp_do_get_boundary_ad.h
FMS/mpp/include/mpp_type_nocomm.h
FMS/mpp/include/mpp_type_sma.h
FMS/mpp/include/mpp_reduce_nocomm.h
FMS/mpp/include/mpp_do_update_ad.h
FMS/mpp/include/mpp_do_redistribute.h
FMS/mpp/include/mpp_do_updateV_ad.h
FMS/mpp/include/mpp_alltoall_sma.h
FMS/mpp/include/mpp_read_compressed.h
FMS/mpp/include/mpp_chksum.h
FMS/mpp/include/mpp_global_field_ad.h
FMS/mpp/include/mpp_do_update_nonblock.h
FMS/mpp/include/mpp_sum_nocomm_ad.h
FMS/mpp/include/mpp_update_nest_domains.h
FMS/mpp/include/mpp_sum_mpi_ad.h
FMS/mpp/include/mpp_reduce_mpi.h
FMS/mpp/include/mpp_gather.h
FMS/mpp/include/mpp_global_reduce.h
FMS/mpp/include/mpp_do_global_field_ad.h
FMS/mpp/include/mpp_transmit_sma.h
FMS/mpp/include/mpp_chksum_int.h
FMS/mpp/include/mpp_global_field_ug.h
FMS/mpp/include/mpp_do_updateV.h
FMS/mpp/include/mpp_global_sum_tl.h
FMS/mpp/include/mpp_chksum_scalar.h
FMS/mpp/include/mpp_write_compressed.h
FMS/mpp/include/mpp_sum_mpi.h
FMS/mpp/include/mpp_alltoall_mpi.h
FMS/mpp/include/mpp_error_s_a.h
FMS/mpp/include/mpp_do_updateV_nonblock.h
FMS/mpp/include/mpp_do_check.h
FMS/mpp/include/mpp_update_domains2D.h
FMS/mpp/include/mpp_sum_sma.h
FMS/mpp/include/mpp_group_update.h
FMS/mpp/include/mpp_get_boundary.h
FMS/mpp/include/mpp_error_a_s.h
FMS/mpp/include/mpp_get_boundary_ad.h
FMS/mpp/include/mpp_do_get_boundary.h
FMS/mpp/include/mpp_global_field.h
FMS/mpp/include/system_clock.h
FMS/mpp/include/mpp_type_mpi.h
FMS/mpp/include/mpp_transmit_nocomm.h
FMS/mpp/include/mpp_scatter.h
FMS/mpp/include/mpp_do_update_nest.h
FMS/mpp/include/mpp_read_2Ddecomp.h
FMS/mpp/include/mpp_error_s_s.h
FMS/mpp/include/mpp_global_sum_ad.h
FMS/mpp/include/mpp_update_domains2D_nonblock.h
FMS/mpp/include/mpp_do_update.h
FMS/mosaic/gradient_c2l.h
FMS/mosaic/interp.h
FMS/mosaic/mosaic_util.h
FMS/mosaic/constant.h
FMS/mosaic/read_mosaic.h
FMS/mosaic/create_xgrid.h
FMS/drifters/fms_switches.h
FMS/drifters/drifters_set_field.h
FMS/drifters/drifters_compute_k.h
FMS/drifters/drifters_push.h
FMS/include/fms_platform.h
FMS/include/file_version.h
)
